name: Terraform CI

# Kích hoạt workflow khi có push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Quyền cần thiết cho workflow
permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: Terraform Validation and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Format
        run: terraform fmt -check -recursive
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false > terraform-plan-output.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Lưu tệp terraform-plan-output.txt dưới dạng artifact
      - name: Upload Terraform Plan output
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-output
          path: terraform-plan-output.txt

      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const output = `${{ steps.plan.outputs.stdout }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan Output\n\`\`\`\n${output}\n\`\`\``
            });

  save-plan-output:
    name: Save Terraform Plan Output
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # Tải tệp terraform-plan-output.txt từ artifact
      - name: Download Terraform Plan output
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-output

      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Create or checkout terraform-plan-output branch
        run: |
          git checkout -b terraform-plan-output || git checkout terraform-plan-output

      - name: Commit and push to terraform-plan-output branch
        run: |
          git add terraform-plan-output.txt
          git commit -m "Update Terraform Plan output - $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          git push origin terraform-plan-output --force