name: Terraform CI

# Kích hoạt workflow khi có push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Quyền cần thiết cho workflow
permissions:
  contents: read
  pull-requests: write  # Để thêm bình luận trên pull request

jobs:
  terraform:
    name: Terraform Validation and Plan
    runs-on: ubuntu-latest

    # Định nghĩa các bước trong job
    steps:
      # Kiểm tra mã nguồn từ kho lưu trữ
      - name: Checkout repository
        uses: actions/checkout@v4

      # Thiết lập Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Chỉ định phiên bản Terraform phù hợp

      # Khởi tạo Terraform
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Kiểm tra định dạng mã
      - name: Terraform Format
        run: terraform fmt -check -recursive
        continue-on-error: false  # Thất bại nếu định dạng không đúng

      # Xác thực mã Terraform
      - name: Terraform Validate
        run: terraform validate

      # Tạo kế hoạch Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Bình luận kết quả Terraform Plan trên Pull Request
      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const output = `${{ steps.plan.outputs.stdout }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan Output\n\`\`\`\n${output}\n\`\`\``
            });